/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const order_benvy: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const register_virtual_glb_asset: (a: number, b: number, c: number, d: number) => void;
export const spawn_imported_entity: (a: number, b: number) => void;
export const toggle_rigging_mode: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1c2d65ca8bdd7da2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hdda7b6e24b219676: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1a86770ad3c91a64: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h28a46cc16efee1bb_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hee949aa9b4749057: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2d0fb4c3456fe2a3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hf294e26e283a81bc: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
